/*
Digital.ai Release API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConfigurationFacet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigurationFacet{}

// ConfigurationFacet struct for ConfigurationFacet
type ConfigurationFacet struct {
	Scope *FacetScope `json:"scope,omitempty"`
	TargetId *string `json:"targetId,omitempty"`
	ConfigurationUri *string `json:"configurationUri,omitempty"`
	VariableMapping *map[string]string `json:"variableMapping,omitempty"`
	VariableUsages []UsagePoint `json:"variableUsages,omitempty"`
	PropertiesWithVariables []interface{} `json:"propertiesWithVariables,omitempty"`
}

// NewConfigurationFacet instantiates a new ConfigurationFacet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigurationFacet() *ConfigurationFacet {
	this := ConfigurationFacet{}
	return &this
}

// NewConfigurationFacetWithDefaults instantiates a new ConfigurationFacet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigurationFacetWithDefaults() *ConfigurationFacet {
	this := ConfigurationFacet{}
	return &this
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *ConfigurationFacet) GetScope() FacetScope {
	if o == nil || isNil(o.Scope) {
		var ret FacetScope
		return ret
	}
	return *o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationFacet) GetScopeOk() (*FacetScope, bool) {
	if o == nil || isNil(o.Scope) {
		return nil, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *ConfigurationFacet) HasScope() bool {
	if o != nil && !isNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given FacetScope and assigns it to the Scope field.
func (o *ConfigurationFacet) SetScope(v FacetScope) {
	o.Scope = &v
}

// GetTargetId returns the TargetId field value if set, zero value otherwise.
func (o *ConfigurationFacet) GetTargetId() string {
	if o == nil || isNil(o.TargetId) {
		var ret string
		return ret
	}
	return *o.TargetId
}

// GetTargetIdOk returns a tuple with the TargetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationFacet) GetTargetIdOk() (*string, bool) {
	if o == nil || isNil(o.TargetId) {
		return nil, false
	}
	return o.TargetId, true
}

// HasTargetId returns a boolean if a field has been set.
func (o *ConfigurationFacet) HasTargetId() bool {
	if o != nil && !isNil(o.TargetId) {
		return true
	}

	return false
}

// SetTargetId gets a reference to the given string and assigns it to the TargetId field.
func (o *ConfigurationFacet) SetTargetId(v string) {
	o.TargetId = &v
}

// GetConfigurationUri returns the ConfigurationUri field value if set, zero value otherwise.
func (o *ConfigurationFacet) GetConfigurationUri() string {
	if o == nil || isNil(o.ConfigurationUri) {
		var ret string
		return ret
	}
	return *o.ConfigurationUri
}

// GetConfigurationUriOk returns a tuple with the ConfigurationUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationFacet) GetConfigurationUriOk() (*string, bool) {
	if o == nil || isNil(o.ConfigurationUri) {
		return nil, false
	}
	return o.ConfigurationUri, true
}

// HasConfigurationUri returns a boolean if a field has been set.
func (o *ConfigurationFacet) HasConfigurationUri() bool {
	if o != nil && !isNil(o.ConfigurationUri) {
		return true
	}

	return false
}

// SetConfigurationUri gets a reference to the given string and assigns it to the ConfigurationUri field.
func (o *ConfigurationFacet) SetConfigurationUri(v string) {
	o.ConfigurationUri = &v
}

// GetVariableMapping returns the VariableMapping field value if set, zero value otherwise.
func (o *ConfigurationFacet) GetVariableMapping() map[string]string {
	if o == nil || isNil(o.VariableMapping) {
		var ret map[string]string
		return ret
	}
	return *o.VariableMapping
}

// GetVariableMappingOk returns a tuple with the VariableMapping field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationFacet) GetVariableMappingOk() (*map[string]string, bool) {
	if o == nil || isNil(o.VariableMapping) {
		return nil, false
	}
	return o.VariableMapping, true
}

// HasVariableMapping returns a boolean if a field has been set.
func (o *ConfigurationFacet) HasVariableMapping() bool {
	if o != nil && !isNil(o.VariableMapping) {
		return true
	}

	return false
}

// SetVariableMapping gets a reference to the given map[string]string and assigns it to the VariableMapping field.
func (o *ConfigurationFacet) SetVariableMapping(v map[string]string) {
	o.VariableMapping = &v
}

// GetVariableUsages returns the VariableUsages field value if set, zero value otherwise.
func (o *ConfigurationFacet) GetVariableUsages() []UsagePoint {
	if o == nil || isNil(o.VariableUsages) {
		var ret []UsagePoint
		return ret
	}
	return o.VariableUsages
}

// GetVariableUsagesOk returns a tuple with the VariableUsages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationFacet) GetVariableUsagesOk() ([]UsagePoint, bool) {
	if o == nil || isNil(o.VariableUsages) {
		return nil, false
	}
	return o.VariableUsages, true
}

// HasVariableUsages returns a boolean if a field has been set.
func (o *ConfigurationFacet) HasVariableUsages() bool {
	if o != nil && !isNil(o.VariableUsages) {
		return true
	}

	return false
}

// SetVariableUsages gets a reference to the given []UsagePoint and assigns it to the VariableUsages field.
func (o *ConfigurationFacet) SetVariableUsages(v []UsagePoint) {
	o.VariableUsages = v
}

// GetPropertiesWithVariables returns the PropertiesWithVariables field value if set, zero value otherwise.
func (o *ConfigurationFacet) GetPropertiesWithVariables() []interface{} {
	if o == nil || isNil(o.PropertiesWithVariables) {
		var ret []interface{}
		return ret
	}
	return o.PropertiesWithVariables
}

// GetPropertiesWithVariablesOk returns a tuple with the PropertiesWithVariables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationFacet) GetPropertiesWithVariablesOk() ([]interface{}, bool) {
	if o == nil || isNil(o.PropertiesWithVariables) {
		return nil, false
	}
	return o.PropertiesWithVariables, true
}

// HasPropertiesWithVariables returns a boolean if a field has been set.
func (o *ConfigurationFacet) HasPropertiesWithVariables() bool {
	if o != nil && !isNil(o.PropertiesWithVariables) {
		return true
	}

	return false
}

// SetPropertiesWithVariables gets a reference to the given []interface{} and assigns it to the PropertiesWithVariables field.
func (o *ConfigurationFacet) SetPropertiesWithVariables(v []interface{}) {
	o.PropertiesWithVariables = v
}

func (o ConfigurationFacet) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigurationFacet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	if !isNil(o.TargetId) {
		toSerialize["targetId"] = o.TargetId
	}
	if !isNil(o.ConfigurationUri) {
		toSerialize["configurationUri"] = o.ConfigurationUri
	}
	if !isNil(o.VariableMapping) {
		toSerialize["variableMapping"] = o.VariableMapping
	}
	if !isNil(o.VariableUsages) {
		toSerialize["variableUsages"] = o.VariableUsages
	}
	if !isNil(o.PropertiesWithVariables) {
		toSerialize["propertiesWithVariables"] = o.PropertiesWithVariables
	}
	return toSerialize, nil
}

type NullableConfigurationFacet struct {
	value *ConfigurationFacet
	isSet bool
}

func (v NullableConfigurationFacet) Get() *ConfigurationFacet {
	return v.value
}

func (v *NullableConfigurationFacet) Set(val *ConfigurationFacet) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigurationFacet) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigurationFacet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigurationFacet(val *ConfigurationFacet) *NullableConfigurationFacet {
	return &NullableConfigurationFacet{value: val, isSet: true}
}

func (v NullableConfigurationFacet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigurationFacet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


