/*
Digital.ai Release API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EnvironmentLabelView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvironmentLabelView{}

// EnvironmentLabelView struct for EnvironmentLabelView
type EnvironmentLabelView struct {
	Id    *string `json:"id,omitempty"`
	Title *string `json:"title,omitempty"`
	Color *string `json:"color,omitempty"`
}

// NewEnvironmentLabelView instantiates a new EnvironmentLabelView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentLabelView() *EnvironmentLabelView {
	this := EnvironmentLabelView{}
	return &this
}

// NewEnvironmentLabelViewWithDefaults instantiates a new EnvironmentLabelView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentLabelViewWithDefaults() *EnvironmentLabelView {
	this := EnvironmentLabelView{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EnvironmentLabelView) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentLabelView) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EnvironmentLabelView) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *EnvironmentLabelView) SetId(v string) {
	o.Id = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *EnvironmentLabelView) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentLabelView) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *EnvironmentLabelView) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *EnvironmentLabelView) SetTitle(v string) {
	o.Title = &v
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *EnvironmentLabelView) GetColor() string {
	if o == nil || IsNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentLabelView) GetColorOk() (*string, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *EnvironmentLabelView) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *EnvironmentLabelView) SetColor(v string) {
	o.Color = &v
}

func (o EnvironmentLabelView) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvironmentLabelView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	return toSerialize, nil
}

type NullableEnvironmentLabelView struct {
	value *EnvironmentLabelView
	isSet bool
}

func (v NullableEnvironmentLabelView) Get() *EnvironmentLabelView {
	return v.value
}

func (v *NullableEnvironmentLabelView) Set(val *EnvironmentLabelView) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentLabelView) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentLabelView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentLabelView(val *EnvironmentLabelView) *NullableEnvironmentLabelView {
	return &NullableEnvironmentLabelView{value: val, isSet: true}
}

func (v NullableEnvironmentLabelView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentLabelView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
