/*
Digital.ai Release API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FolderVariables type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FolderVariables{}

// FolderVariables struct for FolderVariables
type FolderVariables struct {
	Variables []Variable `json:"variables,omitempty"`
	StringVariableValues *map[string]string `json:"stringVariableValues,omitempty"`
	PasswordVariableValues *map[string]string `json:"passwordVariableValues,omitempty"`
	VariablesByKeys *map[string]Variable `json:"variablesByKeys,omitempty"`
}

// NewFolderVariables instantiates a new FolderVariables object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFolderVariables() *FolderVariables {
	this := FolderVariables{}
	return &this
}

// NewFolderVariablesWithDefaults instantiates a new FolderVariables object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFolderVariablesWithDefaults() *FolderVariables {
	this := FolderVariables{}
	return &this
}

// GetVariables returns the Variables field value if set, zero value otherwise.
func (o *FolderVariables) GetVariables() []Variable {
	if o == nil || isNil(o.Variables) {
		var ret []Variable
		return ret
	}
	return o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FolderVariables) GetVariablesOk() ([]Variable, bool) {
	if o == nil || isNil(o.Variables) {
		return nil, false
	}
	return o.Variables, true
}

// HasVariables returns a boolean if a field has been set.
func (o *FolderVariables) HasVariables() bool {
	if o != nil && !isNil(o.Variables) {
		return true
	}

	return false
}

// SetVariables gets a reference to the given []Variable and assigns it to the Variables field.
func (o *FolderVariables) SetVariables(v []Variable) {
	o.Variables = v
}

// GetStringVariableValues returns the StringVariableValues field value if set, zero value otherwise.
func (o *FolderVariables) GetStringVariableValues() map[string]string {
	if o == nil || isNil(o.StringVariableValues) {
		var ret map[string]string
		return ret
	}
	return *o.StringVariableValues
}

// GetStringVariableValuesOk returns a tuple with the StringVariableValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FolderVariables) GetStringVariableValuesOk() (*map[string]string, bool) {
	if o == nil || isNil(o.StringVariableValues) {
		return nil, false
	}
	return o.StringVariableValues, true
}

// HasStringVariableValues returns a boolean if a field has been set.
func (o *FolderVariables) HasStringVariableValues() bool {
	if o != nil && !isNil(o.StringVariableValues) {
		return true
	}

	return false
}

// SetStringVariableValues gets a reference to the given map[string]string and assigns it to the StringVariableValues field.
func (o *FolderVariables) SetStringVariableValues(v map[string]string) {
	o.StringVariableValues = &v
}

// GetPasswordVariableValues returns the PasswordVariableValues field value if set, zero value otherwise.
func (o *FolderVariables) GetPasswordVariableValues() map[string]string {
	if o == nil || isNil(o.PasswordVariableValues) {
		var ret map[string]string
		return ret
	}
	return *o.PasswordVariableValues
}

// GetPasswordVariableValuesOk returns a tuple with the PasswordVariableValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FolderVariables) GetPasswordVariableValuesOk() (*map[string]string, bool) {
	if o == nil || isNil(o.PasswordVariableValues) {
		return nil, false
	}
	return o.PasswordVariableValues, true
}

// HasPasswordVariableValues returns a boolean if a field has been set.
func (o *FolderVariables) HasPasswordVariableValues() bool {
	if o != nil && !isNil(o.PasswordVariableValues) {
		return true
	}

	return false
}

// SetPasswordVariableValues gets a reference to the given map[string]string and assigns it to the PasswordVariableValues field.
func (o *FolderVariables) SetPasswordVariableValues(v map[string]string) {
	o.PasswordVariableValues = &v
}

// GetVariablesByKeys returns the VariablesByKeys field value if set, zero value otherwise.
func (o *FolderVariables) GetVariablesByKeys() map[string]Variable {
	if o == nil || isNil(o.VariablesByKeys) {
		var ret map[string]Variable
		return ret
	}
	return *o.VariablesByKeys
}

// GetVariablesByKeysOk returns a tuple with the VariablesByKeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FolderVariables) GetVariablesByKeysOk() (*map[string]Variable, bool) {
	if o == nil || isNil(o.VariablesByKeys) {
		return nil, false
	}
	return o.VariablesByKeys, true
}

// HasVariablesByKeys returns a boolean if a field has been set.
func (o *FolderVariables) HasVariablesByKeys() bool {
	if o != nil && !isNil(o.VariablesByKeys) {
		return true
	}

	return false
}

// SetVariablesByKeys gets a reference to the given map[string]Variable and assigns it to the VariablesByKeys field.
func (o *FolderVariables) SetVariablesByKeys(v map[string]Variable) {
	o.VariablesByKeys = &v
}

func (o FolderVariables) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FolderVariables) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Variables) {
		toSerialize["variables"] = o.Variables
	}
	if !isNil(o.StringVariableValues) {
		toSerialize["stringVariableValues"] = o.StringVariableValues
	}
	if !isNil(o.PasswordVariableValues) {
		toSerialize["passwordVariableValues"] = o.PasswordVariableValues
	}
	if !isNil(o.VariablesByKeys) {
		toSerialize["variablesByKeys"] = o.VariablesByKeys
	}
	return toSerialize, nil
}

type NullableFolderVariables struct {
	value *FolderVariables
	isSet bool
}

func (v NullableFolderVariables) Get() *FolderVariables {
	return v.value
}

func (v *NullableFolderVariables) Set(val *FolderVariables) {
	v.value = val
	v.isSet = true
}

func (v NullableFolderVariables) IsSet() bool {
	return v.isSet
}

func (v *NullableFolderVariables) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFolderVariables(val *FolderVariables) *NullableFolderVariables {
	return &NullableFolderVariables{value: val, isSet: true}
}

func (v NullableFolderVariables) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFolderVariables) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


