/*
Digital.ai Release API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PrincipalView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrincipalView{}

// PrincipalView struct for PrincipalView
type PrincipalView struct {
	Username *string `json:"username,omitempty"`
	Fullname *string `json:"fullname,omitempty"`
}

// NewPrincipalView instantiates a new PrincipalView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrincipalView() *PrincipalView {
	this := PrincipalView{}
	return &this
}

// NewPrincipalViewWithDefaults instantiates a new PrincipalView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrincipalViewWithDefaults() *PrincipalView {
	this := PrincipalView{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *PrincipalView) GetUsername() string {
	if o == nil || isNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrincipalView) GetUsernameOk() (*string, bool) {
	if o == nil || isNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *PrincipalView) HasUsername() bool {
	if o != nil && !isNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *PrincipalView) SetUsername(v string) {
	o.Username = &v
}

// GetFullname returns the Fullname field value if set, zero value otherwise.
func (o *PrincipalView) GetFullname() string {
	if o == nil || isNil(o.Fullname) {
		var ret string
		return ret
	}
	return *o.Fullname
}

// GetFullnameOk returns a tuple with the Fullname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrincipalView) GetFullnameOk() (*string, bool) {
	if o == nil || isNil(o.Fullname) {
		return nil, false
	}
	return o.Fullname, true
}

// HasFullname returns a boolean if a field has been set.
func (o *PrincipalView) HasFullname() bool {
	if o != nil && !isNil(o.Fullname) {
		return true
	}

	return false
}

// SetFullname gets a reference to the given string and assigns it to the Fullname field.
func (o *PrincipalView) SetFullname(v string) {
	o.Fullname = &v
}

func (o PrincipalView) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrincipalView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !isNil(o.Fullname) {
		toSerialize["fullname"] = o.Fullname
	}
	return toSerialize, nil
}

type NullablePrincipalView struct {
	value *PrincipalView
	isSet bool
}

func (v NullablePrincipalView) Get() *PrincipalView {
	return v.value
}

func (v *NullablePrincipalView) Set(val *PrincipalView) {
	v.value = val
	v.isSet = true
}

func (v NullablePrincipalView) IsSet() bool {
	return v.isSet
}

func (v *NullablePrincipalView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrincipalView(val *PrincipalView) *NullablePrincipalView {
	return &NullablePrincipalView{value: val, isSet: true}
}

func (v NullablePrincipalView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrincipalView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


