/*
Digital.ai Release API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the PlanItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlanItem{}

// PlanItem struct for PlanItem
type PlanItem struct {
	Id                      *string                `json:"id,omitempty"`
	Type                    *string                `json:"type,omitempty"`
	Title                   *string                `json:"title,omitempty"`
	Description             *string                `json:"description,omitempty"`
	Owner                   *string                `json:"owner,omitempty"`
	ScheduledStartDate      *time.Time             `json:"scheduledStartDate,omitempty"`
	DueDate                 *time.Time             `json:"dueDate,omitempty"`
	StartDate               *time.Time             `json:"startDate,omitempty"`
	EndDate                 *time.Time             `json:"endDate,omitempty"`
	PlannedDuration         *int32                 `json:"plannedDuration,omitempty"`
	FlagStatus              *FlagStatus            `json:"flagStatus,omitempty"`
	FlagComment             *string                `json:"flagComment,omitempty"`
	OverdueNotified         *bool                  `json:"overdueNotified,omitempty"`
	Flagged                 *bool                  `json:"flagged,omitempty"`
	StartOrScheduledDate    *time.Time             `json:"startOrScheduledDate,omitempty"`
	EndOrDueDate            *time.Time             `json:"endOrDueDate,omitempty"`
	Children                []PlanItem             `json:"children,omitempty"`
	Overdue                 *bool                  `json:"overdue,omitempty"`
	Done                    *bool                  `json:"done,omitempty"`
	Release                 *Release               `json:"release,omitempty"`
	ReleaseUid              *int32                 `json:"releaseUid,omitempty"`
	Updatable               *bool                  `json:"updatable,omitempty"`
	DisplayPath             *string                `json:"displayPath,omitempty"`
	Aborted                 *bool                  `json:"aborted,omitempty"`
	Active                  *bool                  `json:"active,omitempty"`
	VariableUsages          []UsagePoint           `json:"variableUsages,omitempty"`
	OrCalculateDueDate      NullableTime           `json:"orCalculateDueDate,omitempty"`
	ComputedPlannedDuration map[string]interface{} `json:"computedPlannedDuration,omitempty"`
	ActualDuration          map[string]interface{} `json:"actualDuration,omitempty"`
}

// NewPlanItem instantiates a new PlanItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlanItem() *PlanItem {
	this := PlanItem{}
	return &this
}

// NewPlanItemWithDefaults instantiates a new PlanItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlanItemWithDefaults() *PlanItem {
	this := PlanItem{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PlanItem) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanItem) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PlanItem) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PlanItem) SetId(v string) {
	o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *PlanItem) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanItem) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *PlanItem) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *PlanItem) SetType(v string) {
	o.Type = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *PlanItem) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanItem) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *PlanItem) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *PlanItem) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PlanItem) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanItem) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PlanItem) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PlanItem) SetDescription(v string) {
	o.Description = &v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *PlanItem) GetOwner() string {
	if o == nil || IsNil(o.Owner) {
		var ret string
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanItem) GetOwnerOk() (*string, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *PlanItem) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given string and assigns it to the Owner field.
func (o *PlanItem) SetOwner(v string) {
	o.Owner = &v
}

// GetScheduledStartDate returns the ScheduledStartDate field value if set, zero value otherwise.
func (o *PlanItem) GetScheduledStartDate() time.Time {
	if o == nil || IsNil(o.ScheduledStartDate) {
		var ret time.Time
		return ret
	}
	return *o.ScheduledStartDate
}

// GetScheduledStartDateOk returns a tuple with the ScheduledStartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanItem) GetScheduledStartDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ScheduledStartDate) {
		return nil, false
	}
	return o.ScheduledStartDate, true
}

// HasScheduledStartDate returns a boolean if a field has been set.
func (o *PlanItem) HasScheduledStartDate() bool {
	if o != nil && !IsNil(o.ScheduledStartDate) {
		return true
	}

	return false
}

// SetScheduledStartDate gets a reference to the given time.Time and assigns it to the ScheduledStartDate field.
func (o *PlanItem) SetScheduledStartDate(v time.Time) {
	o.ScheduledStartDate = &v
}

// GetDueDate returns the DueDate field value if set, zero value otherwise.
func (o *PlanItem) GetDueDate() time.Time {
	if o == nil || IsNil(o.DueDate) {
		var ret time.Time
		return ret
	}
	return *o.DueDate
}

// GetDueDateOk returns a tuple with the DueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanItem) GetDueDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DueDate) {
		return nil, false
	}
	return o.DueDate, true
}

// HasDueDate returns a boolean if a field has been set.
func (o *PlanItem) HasDueDate() bool {
	if o != nil && !IsNil(o.DueDate) {
		return true
	}

	return false
}

// SetDueDate gets a reference to the given time.Time and assigns it to the DueDate field.
func (o *PlanItem) SetDueDate(v time.Time) {
	o.DueDate = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *PlanItem) GetStartDate() time.Time {
	if o == nil || IsNil(o.StartDate) {
		var ret time.Time
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanItem) GetStartDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *PlanItem) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given time.Time and assigns it to the StartDate field.
func (o *PlanItem) SetStartDate(v time.Time) {
	o.StartDate = &v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *PlanItem) GetEndDate() time.Time {
	if o == nil || IsNil(o.EndDate) {
		var ret time.Time
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanItem) GetEndDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *PlanItem) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given time.Time and assigns it to the EndDate field.
func (o *PlanItem) SetEndDate(v time.Time) {
	o.EndDate = &v
}

// GetPlannedDuration returns the PlannedDuration field value if set, zero value otherwise.
func (o *PlanItem) GetPlannedDuration() int32 {
	if o == nil || IsNil(o.PlannedDuration) {
		var ret int32
		return ret
	}
	return *o.PlannedDuration
}

// GetPlannedDurationOk returns a tuple with the PlannedDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanItem) GetPlannedDurationOk() (*int32, bool) {
	if o == nil || IsNil(o.PlannedDuration) {
		return nil, false
	}
	return o.PlannedDuration, true
}

// HasPlannedDuration returns a boolean if a field has been set.
func (o *PlanItem) HasPlannedDuration() bool {
	if o != nil && !IsNil(o.PlannedDuration) {
		return true
	}

	return false
}

// SetPlannedDuration gets a reference to the given int32 and assigns it to the PlannedDuration field.
func (o *PlanItem) SetPlannedDuration(v int32) {
	o.PlannedDuration = &v
}

// GetFlagStatus returns the FlagStatus field value if set, zero value otherwise.
func (o *PlanItem) GetFlagStatus() FlagStatus {
	if o == nil || IsNil(o.FlagStatus) {
		var ret FlagStatus
		return ret
	}
	return *o.FlagStatus
}

// GetFlagStatusOk returns a tuple with the FlagStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanItem) GetFlagStatusOk() (*FlagStatus, bool) {
	if o == nil || IsNil(o.FlagStatus) {
		return nil, false
	}
	return o.FlagStatus, true
}

// HasFlagStatus returns a boolean if a field has been set.
func (o *PlanItem) HasFlagStatus() bool {
	if o != nil && !IsNil(o.FlagStatus) {
		return true
	}

	return false
}

// SetFlagStatus gets a reference to the given FlagStatus and assigns it to the FlagStatus field.
func (o *PlanItem) SetFlagStatus(v FlagStatus) {
	o.FlagStatus = &v
}

// GetFlagComment returns the FlagComment field value if set, zero value otherwise.
func (o *PlanItem) GetFlagComment() string {
	if o == nil || IsNil(o.FlagComment) {
		var ret string
		return ret
	}
	return *o.FlagComment
}

// GetFlagCommentOk returns a tuple with the FlagComment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanItem) GetFlagCommentOk() (*string, bool) {
	if o == nil || IsNil(o.FlagComment) {
		return nil, false
	}
	return o.FlagComment, true
}

// HasFlagComment returns a boolean if a field has been set.
func (o *PlanItem) HasFlagComment() bool {
	if o != nil && !IsNil(o.FlagComment) {
		return true
	}

	return false
}

// SetFlagComment gets a reference to the given string and assigns it to the FlagComment field.
func (o *PlanItem) SetFlagComment(v string) {
	o.FlagComment = &v
}

// GetOverdueNotified returns the OverdueNotified field value if set, zero value otherwise.
func (o *PlanItem) GetOverdueNotified() bool {
	if o == nil || IsNil(o.OverdueNotified) {
		var ret bool
		return ret
	}
	return *o.OverdueNotified
}

// GetOverdueNotifiedOk returns a tuple with the OverdueNotified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanItem) GetOverdueNotifiedOk() (*bool, bool) {
	if o == nil || IsNil(o.OverdueNotified) {
		return nil, false
	}
	return o.OverdueNotified, true
}

// HasOverdueNotified returns a boolean if a field has been set.
func (o *PlanItem) HasOverdueNotified() bool {
	if o != nil && !IsNil(o.OverdueNotified) {
		return true
	}

	return false
}

// SetOverdueNotified gets a reference to the given bool and assigns it to the OverdueNotified field.
func (o *PlanItem) SetOverdueNotified(v bool) {
	o.OverdueNotified = &v
}

// GetFlagged returns the Flagged field value if set, zero value otherwise.
func (o *PlanItem) GetFlagged() bool {
	if o == nil || IsNil(o.Flagged) {
		var ret bool
		return ret
	}
	return *o.Flagged
}

// GetFlaggedOk returns a tuple with the Flagged field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanItem) GetFlaggedOk() (*bool, bool) {
	if o == nil || IsNil(o.Flagged) {
		return nil, false
	}
	return o.Flagged, true
}

// HasFlagged returns a boolean if a field has been set.
func (o *PlanItem) HasFlagged() bool {
	if o != nil && !IsNil(o.Flagged) {
		return true
	}

	return false
}

// SetFlagged gets a reference to the given bool and assigns it to the Flagged field.
func (o *PlanItem) SetFlagged(v bool) {
	o.Flagged = &v
}

// GetStartOrScheduledDate returns the StartOrScheduledDate field value if set, zero value otherwise.
func (o *PlanItem) GetStartOrScheduledDate() time.Time {
	if o == nil || IsNil(o.StartOrScheduledDate) {
		var ret time.Time
		return ret
	}
	return *o.StartOrScheduledDate
}

// GetStartOrScheduledDateOk returns a tuple with the StartOrScheduledDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanItem) GetStartOrScheduledDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartOrScheduledDate) {
		return nil, false
	}
	return o.StartOrScheduledDate, true
}

// HasStartOrScheduledDate returns a boolean if a field has been set.
func (o *PlanItem) HasStartOrScheduledDate() bool {
	if o != nil && !IsNil(o.StartOrScheduledDate) {
		return true
	}

	return false
}

// SetStartOrScheduledDate gets a reference to the given time.Time and assigns it to the StartOrScheduledDate field.
func (o *PlanItem) SetStartOrScheduledDate(v time.Time) {
	o.StartOrScheduledDate = &v
}

// GetEndOrDueDate returns the EndOrDueDate field value if set, zero value otherwise.
func (o *PlanItem) GetEndOrDueDate() time.Time {
	if o == nil || IsNil(o.EndOrDueDate) {
		var ret time.Time
		return ret
	}
	return *o.EndOrDueDate
}

// GetEndOrDueDateOk returns a tuple with the EndOrDueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanItem) GetEndOrDueDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndOrDueDate) {
		return nil, false
	}
	return o.EndOrDueDate, true
}

// HasEndOrDueDate returns a boolean if a field has been set.
func (o *PlanItem) HasEndOrDueDate() bool {
	if o != nil && !IsNil(o.EndOrDueDate) {
		return true
	}

	return false
}

// SetEndOrDueDate gets a reference to the given time.Time and assigns it to the EndOrDueDate field.
func (o *PlanItem) SetEndOrDueDate(v time.Time) {
	o.EndOrDueDate = &v
}

// GetChildren returns the Children field value if set, zero value otherwise.
func (o *PlanItem) GetChildren() []PlanItem {
	if o == nil || IsNil(o.Children) {
		var ret []PlanItem
		return ret
	}
	return o.Children
}

// GetChildrenOk returns a tuple with the Children field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanItem) GetChildrenOk() ([]PlanItem, bool) {
	if o == nil || IsNil(o.Children) {
		return nil, false
	}
	return o.Children, true
}

// HasChildren returns a boolean if a field has been set.
func (o *PlanItem) HasChildren() bool {
	if o != nil && !IsNil(o.Children) {
		return true
	}

	return false
}

// SetChildren gets a reference to the given []PlanItem and assigns it to the Children field.
func (o *PlanItem) SetChildren(v []PlanItem) {
	o.Children = v
}

// GetOverdue returns the Overdue field value if set, zero value otherwise.
func (o *PlanItem) GetOverdue() bool {
	if o == nil || IsNil(o.Overdue) {
		var ret bool
		return ret
	}
	return *o.Overdue
}

// GetOverdueOk returns a tuple with the Overdue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanItem) GetOverdueOk() (*bool, bool) {
	if o == nil || IsNil(o.Overdue) {
		return nil, false
	}
	return o.Overdue, true
}

// HasOverdue returns a boolean if a field has been set.
func (o *PlanItem) HasOverdue() bool {
	if o != nil && !IsNil(o.Overdue) {
		return true
	}

	return false
}

// SetOverdue gets a reference to the given bool and assigns it to the Overdue field.
func (o *PlanItem) SetOverdue(v bool) {
	o.Overdue = &v
}

// GetDone returns the Done field value if set, zero value otherwise.
func (o *PlanItem) GetDone() bool {
	if o == nil || IsNil(o.Done) {
		var ret bool
		return ret
	}
	return *o.Done
}

// GetDoneOk returns a tuple with the Done field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanItem) GetDoneOk() (*bool, bool) {
	if o == nil || IsNil(o.Done) {
		return nil, false
	}
	return o.Done, true
}

// HasDone returns a boolean if a field has been set.
func (o *PlanItem) HasDone() bool {
	if o != nil && !IsNil(o.Done) {
		return true
	}

	return false
}

// SetDone gets a reference to the given bool and assigns it to the Done field.
func (o *PlanItem) SetDone(v bool) {
	o.Done = &v
}

// GetRelease returns the Release field value if set, zero value otherwise.
func (o *PlanItem) GetRelease() Release {
	if o == nil || IsNil(o.Release) {
		var ret Release
		return ret
	}
	return *o.Release
}

// GetReleaseOk returns a tuple with the Release field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanItem) GetReleaseOk() (*Release, bool) {
	if o == nil || IsNil(o.Release) {
		return nil, false
	}
	return o.Release, true
}

// HasRelease returns a boolean if a field has been set.
func (o *PlanItem) HasRelease() bool {
	if o != nil && !IsNil(o.Release) {
		return true
	}

	return false
}

// SetRelease gets a reference to the given Release and assigns it to the Release field.
func (o *PlanItem) SetRelease(v Release) {
	o.Release = &v
}

// GetReleaseUid returns the ReleaseUid field value if set, zero value otherwise.
func (o *PlanItem) GetReleaseUid() int32 {
	if o == nil || IsNil(o.ReleaseUid) {
		var ret int32
		return ret
	}
	return *o.ReleaseUid
}

// GetReleaseUidOk returns a tuple with the ReleaseUid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanItem) GetReleaseUidOk() (*int32, bool) {
	if o == nil || IsNil(o.ReleaseUid) {
		return nil, false
	}
	return o.ReleaseUid, true
}

// HasReleaseUid returns a boolean if a field has been set.
func (o *PlanItem) HasReleaseUid() bool {
	if o != nil && !IsNil(o.ReleaseUid) {
		return true
	}

	return false
}

// SetReleaseUid gets a reference to the given int32 and assigns it to the ReleaseUid field.
func (o *PlanItem) SetReleaseUid(v int32) {
	o.ReleaseUid = &v
}

// GetUpdatable returns the Updatable field value if set, zero value otherwise.
func (o *PlanItem) GetUpdatable() bool {
	if o == nil || IsNil(o.Updatable) {
		var ret bool
		return ret
	}
	return *o.Updatable
}

// GetUpdatableOk returns a tuple with the Updatable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanItem) GetUpdatableOk() (*bool, bool) {
	if o == nil || IsNil(o.Updatable) {
		return nil, false
	}
	return o.Updatable, true
}

// HasUpdatable returns a boolean if a field has been set.
func (o *PlanItem) HasUpdatable() bool {
	if o != nil && !IsNil(o.Updatable) {
		return true
	}

	return false
}

// SetUpdatable gets a reference to the given bool and assigns it to the Updatable field.
func (o *PlanItem) SetUpdatable(v bool) {
	o.Updatable = &v
}

// GetDisplayPath returns the DisplayPath field value if set, zero value otherwise.
func (o *PlanItem) GetDisplayPath() string {
	if o == nil || IsNil(o.DisplayPath) {
		var ret string
		return ret
	}
	return *o.DisplayPath
}

// GetDisplayPathOk returns a tuple with the DisplayPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanItem) GetDisplayPathOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayPath) {
		return nil, false
	}
	return o.DisplayPath, true
}

// HasDisplayPath returns a boolean if a field has been set.
func (o *PlanItem) HasDisplayPath() bool {
	if o != nil && !IsNil(o.DisplayPath) {
		return true
	}

	return false
}

// SetDisplayPath gets a reference to the given string and assigns it to the DisplayPath field.
func (o *PlanItem) SetDisplayPath(v string) {
	o.DisplayPath = &v
}

// GetAborted returns the Aborted field value if set, zero value otherwise.
func (o *PlanItem) GetAborted() bool {
	if o == nil || IsNil(o.Aborted) {
		var ret bool
		return ret
	}
	return *o.Aborted
}

// GetAbortedOk returns a tuple with the Aborted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanItem) GetAbortedOk() (*bool, bool) {
	if o == nil || IsNil(o.Aborted) {
		return nil, false
	}
	return o.Aborted, true
}

// HasAborted returns a boolean if a field has been set.
func (o *PlanItem) HasAborted() bool {
	if o != nil && !IsNil(o.Aborted) {
		return true
	}

	return false
}

// SetAborted gets a reference to the given bool and assigns it to the Aborted field.
func (o *PlanItem) SetAborted(v bool) {
	o.Aborted = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *PlanItem) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanItem) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *PlanItem) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *PlanItem) SetActive(v bool) {
	o.Active = &v
}

// GetVariableUsages returns the VariableUsages field value if set, zero value otherwise.
func (o *PlanItem) GetVariableUsages() []UsagePoint {
	if o == nil || IsNil(o.VariableUsages) {
		var ret []UsagePoint
		return ret
	}
	return o.VariableUsages
}

// GetVariableUsagesOk returns a tuple with the VariableUsages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanItem) GetVariableUsagesOk() ([]UsagePoint, bool) {
	if o == nil || IsNil(o.VariableUsages) {
		return nil, false
	}
	return o.VariableUsages, true
}

// HasVariableUsages returns a boolean if a field has been set.
func (o *PlanItem) HasVariableUsages() bool {
	if o != nil && !IsNil(o.VariableUsages) {
		return true
	}

	return false
}

// SetVariableUsages gets a reference to the given []UsagePoint and assigns it to the VariableUsages field.
func (o *PlanItem) SetVariableUsages(v []UsagePoint) {
	o.VariableUsages = v
}

// GetOrCalculateDueDate returns the OrCalculateDueDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlanItem) GetOrCalculateDueDate() time.Time {
	if o == nil || IsNil(o.OrCalculateDueDate.Get()) {
		var ret time.Time
		return ret
	}
	return *o.OrCalculateDueDate.Get()
}

// GetOrCalculateDueDateOk returns a tuple with the OrCalculateDueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlanItem) GetOrCalculateDueDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrCalculateDueDate.Get(), o.OrCalculateDueDate.IsSet()
}

// HasOrCalculateDueDate returns a boolean if a field has been set.
func (o *PlanItem) HasOrCalculateDueDate() bool {
	if o != nil && o.OrCalculateDueDate.IsSet() {
		return true
	}

	return false
}

// SetOrCalculateDueDate gets a reference to the given NullableTime and assigns it to the OrCalculateDueDate field.
func (o *PlanItem) SetOrCalculateDueDate(v time.Time) {
	o.OrCalculateDueDate.Set(&v)
}

// SetOrCalculateDueDateNil sets the value for OrCalculateDueDate to be an explicit nil
func (o *PlanItem) SetOrCalculateDueDateNil() {
	o.OrCalculateDueDate.Set(nil)
}

// UnsetOrCalculateDueDate ensures that no value is present for OrCalculateDueDate, not even an explicit nil
func (o *PlanItem) UnsetOrCalculateDueDate() {
	o.OrCalculateDueDate.Unset()
}

// GetComputedPlannedDuration returns the ComputedPlannedDuration field value if set, zero value otherwise.
func (o *PlanItem) GetComputedPlannedDuration() map[string]interface{} {
	if o == nil || IsNil(o.ComputedPlannedDuration) {
		var ret map[string]interface{}
		return ret
	}
	return o.ComputedPlannedDuration
}

// GetComputedPlannedDurationOk returns a tuple with the ComputedPlannedDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanItem) GetComputedPlannedDurationOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ComputedPlannedDuration) {
		return map[string]interface{}{}, false
	}
	return o.ComputedPlannedDuration, true
}

// HasComputedPlannedDuration returns a boolean if a field has been set.
func (o *PlanItem) HasComputedPlannedDuration() bool {
	if o != nil && !IsNil(o.ComputedPlannedDuration) {
		return true
	}

	return false
}

// SetComputedPlannedDuration gets a reference to the given map[string]interface{} and assigns it to the ComputedPlannedDuration field.
func (o *PlanItem) SetComputedPlannedDuration(v map[string]interface{}) {
	o.ComputedPlannedDuration = v
}

// GetActualDuration returns the ActualDuration field value if set, zero value otherwise.
func (o *PlanItem) GetActualDuration() map[string]interface{} {
	if o == nil || IsNil(o.ActualDuration) {
		var ret map[string]interface{}
		return ret
	}
	return o.ActualDuration
}

// GetActualDurationOk returns a tuple with the ActualDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanItem) GetActualDurationOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ActualDuration) {
		return map[string]interface{}{}, false
	}
	return o.ActualDuration, true
}

// HasActualDuration returns a boolean if a field has been set.
func (o *PlanItem) HasActualDuration() bool {
	if o != nil && !IsNil(o.ActualDuration) {
		return true
	}

	return false
}

// SetActualDuration gets a reference to the given map[string]interface{} and assigns it to the ActualDuration field.
func (o *PlanItem) SetActualDuration(v map[string]interface{}) {
	o.ActualDuration = v
}

func (o PlanItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlanItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}
	if !IsNil(o.ScheduledStartDate) {
		toSerialize["scheduledStartDate"] = o.ScheduledStartDate
	}
	if !IsNil(o.DueDate) {
		toSerialize["dueDate"] = o.DueDate
	}
	if !IsNil(o.StartDate) {
		toSerialize["startDate"] = o.StartDate
	}
	if !IsNil(o.EndDate) {
		toSerialize["endDate"] = o.EndDate
	}
	if !IsNil(o.PlannedDuration) {
		toSerialize["plannedDuration"] = o.PlannedDuration
	}
	if !IsNil(o.FlagStatus) {
		toSerialize["flagStatus"] = o.FlagStatus
	}
	if !IsNil(o.FlagComment) {
		toSerialize["flagComment"] = o.FlagComment
	}
	if !IsNil(o.OverdueNotified) {
		toSerialize["overdueNotified"] = o.OverdueNotified
	}
	if !IsNil(o.Flagged) {
		toSerialize["flagged"] = o.Flagged
	}
	if !IsNil(o.StartOrScheduledDate) {
		toSerialize["startOrScheduledDate"] = o.StartOrScheduledDate
	}
	if !IsNil(o.EndOrDueDate) {
		toSerialize["endOrDueDate"] = o.EndOrDueDate
	}
	if !IsNil(o.Children) {
		toSerialize["children"] = o.Children
	}
	if !IsNil(o.Overdue) {
		toSerialize["overdue"] = o.Overdue
	}
	if !IsNil(o.Done) {
		toSerialize["done"] = o.Done
	}
	if !IsNil(o.Release) {
		toSerialize["release"] = o.Release
	}
	if !IsNil(o.ReleaseUid) {
		toSerialize["releaseUid"] = o.ReleaseUid
	}
	if !IsNil(o.Updatable) {
		toSerialize["updatable"] = o.Updatable
	}
	if !IsNil(o.DisplayPath) {
		toSerialize["displayPath"] = o.DisplayPath
	}
	if !IsNil(o.Aborted) {
		toSerialize["aborted"] = o.Aborted
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.VariableUsages) {
		toSerialize["variableUsages"] = o.VariableUsages
	}
	if o.OrCalculateDueDate.IsSet() {
		toSerialize["orCalculateDueDate"] = o.OrCalculateDueDate.Get()
	}
	if !IsNil(o.ComputedPlannedDuration) {
		toSerialize["computedPlannedDuration"] = o.ComputedPlannedDuration
	}
	if !IsNil(o.ActualDuration) {
		toSerialize["actualDuration"] = o.ActualDuration
	}
	return toSerialize, nil
}

type NullablePlanItem struct {
	value *PlanItem
	isSet bool
}

func (v NullablePlanItem) Get() *PlanItem {
	return v.value
}

func (v *NullablePlanItem) Set(val *PlanItem) {
	v.value = val
	v.isSet = true
}

func (v NullablePlanItem) IsSet() bool {
	return v.isSet
}

func (v *NullablePlanItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlanItem(val *PlanItem) *NullablePlanItem {
	return &NullablePlanItem{value: val, isSet: true}
}

func (v NullablePlanItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlanItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
