name: Build

on:
  push:
    branches:
      - master
      - release/*
  pull_request:

jobs:
  build:
    name: Build Plugin
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Get branch name
        if: contains(github.event.pull_request.labels.*.name, 'release-integration-sdk-go-build')
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Build Project
        run: |
          go mod download
          go build ./...

      - name: Run Tests
        run: |
          go test -cover -v ./...
